### PR TITLE
The standard PHP PSR-2-code applied

### PR DESCRIPTION
**Pull request by jeroendesloovere**
Nothing has technically changed in your code.
I just applied the default PHP code styling by executing the following on the command line:
```php-cs-fixer fix . --level=psr2```

### CODE REVIEW

**Comment by Rvanlaak** [comment]
I'd like this PR to be merged :+1:

**Comment by ajimix** [comment]
Please do another PR and I'll merge it. I can't merge this one as the author deleted the branch.

**Comment by jeroendesloovere** [comment]
@ajimix I restored the branch

**Comment by ajimix** [comment]
Merged in this commit: https://github.com/ajimix/asana-api-php-class/commit/1825929ff4faccb7e1cce1f9f38c157fb358edcb

Thanks!

**Pull request closed without merging**
